version: '3'

services:
    # 定义容器
    redis:
        # 自定义容器名
        container_name: proxy-redis
        image: redis:6
        volumes:
            - /tmp/ProxyPool/redis/data:/data
        expose:
            - "6379"
    proxy:
        container_name: proxy-app
        # 基于Dockerfile制作镜像并创建容器
        build: .
        volumes:
            - /tmp/ProxyPool/logs:/root/ProxyPool/logs
        environment:
            REDIS_URL: redis://@redis:6379/0
        ports:
            - "5555:5555"
        depends_on:
            - redis
